### PR TITLE
Add duplex JACK backend

### PR DESCRIPTION
**Pull request by zamaudio**
Signed-off-by: Damien Zammit <damien@zamaudio.com>

### CODE REVIEW

**Comment by padenot** [comment]
I've looked a this multiple times, and it works fine with Firefox, and passes all cubeb tests, I think we can merge it. Thoughts ?

**Comment by achronop** [comment]
The get current device and enumerate device methods contain static hard coded values. Never the less this is something we can take care later.

**Comment by kinetiknz** [comment]
No objections from me.  I haven't look at it at all, but if it works with in Gecko that's probably an improvement over the current situation.

**Comment by padenot** [comment]
All right, merged, thanks again to @zamaudio ! Now, onto some integration in Firefox.

**Comment by kinetiknz** [comment]
Thanks for working on this!

**Pull request merged**
