### PR TITLE
Fallback to a the default device if the current device has been invalidated, when opening a stream

### PR DESCRIPTION
**Pull request by padenot**
The long-term plan is to implement the device change callback and to be able to disable only a side of the stream, but this prevent locking everything up without informing the user.

If we can't open the device because it's been invalidated, we simply retry with the default device.

### CODE REVIEW

**Comment by padenot** [comment]
@kinetiknz can you have a look ?

**Comment by kinetiknz** [comment]
Why isn't this handled by the caller? If it's done silently inside cubeb, the caller has no knowledge of this happening and can't prevent it or adjust the UI to suit.

**Comment by padenot** [comment]
The real proposal is at #167, this is just a quick something we can do so we can recover.

**Comment by kinetiknz** [comment]
Okay, we can take this (r+ the code changes) but I don't agree with the policy this implements.  Merging since we plan to address this systematically via #167.

**Pull request merged**
