### PR TITLE
Add install and option for not building tests.

### PR DESCRIPTION
**Pull request by mdsitton**
Went ahead and tried to implement a solution for #321 myself, as well implementing install. Any comments?

### CODE REVIEW

**Comment by kinetiknz** [comment]
Thanks, that approach looks fine to me.  Any idea why the CI is rejecting it with the add_executable errors?

**Comment by kinetiknz** [comment]
> Any idea why the CI is rejecting it with the add_executable errors?

Oh, I see, the merge had a conflict where it duplicated the block that was split in 3c77b3b57268fd91aa6b027b12f8eac1ba79fa8b.

**Comment by kinetiknz** [comment]
I fixed the merge issue and rebased your changes in 49b0108038c6852c12db47d849f5fb2237f85bc6, thanks for the patch!

**Comment by mdsitton** [comment]
No problem.

**Pull request closed without merging**
