### PR TITLE
Multi-channels support for windows/mac/linux

### PR DESCRIPTION
**Pull request by jyavenard**
from https://bugzilla.mozilla.org/show_bug.cgi?id=1432779 and https://bugzilla.mozilla.org/show_bug.cgi?id=1431221

### CODE REVIEW

**Comment by padenot** [comment]
I've had a rather extensive look at this on BMO bug #1444479, and it looks good.

**Comment by djg** [comment]
Is this all the patches against [Gecko 1444479](https://bugzil.la/1444479)?

**Comment by padenot** [comment]
Sorry I meant [Gecko bug #1432779 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1432779).

**Comment by padenot** [comment]
And yes, all the patches necessary in cubeb to implement properly what we need here (i.e. multichannel output).

**Pull request merged**
