### PR TITLE
Define KSAUDIO_SPEAKER_5/7POINT1_SURROUND if it doesn't exist

### PR DESCRIPTION
**Pull request by ChunMinChang**
When I try to integrate the multiple channel support of cubeb on Windows, the error says: ```KSAUDIO_SPEAKER_5POINT1_SURROUND is not defined```, so I think it's better to define it in cubeb_wasapi.cpp itself.

### CODE REVIEW

**Comment by padenot** [comment]
Chun-Min, in what configuration does that happen ? Looks good in any case.

**Comment by kinetiknz** [comment]
This shouldn't be necessary and I'd prefer not to add it unless we understand why.  Looking at `ksmedia.h` where these are defined, the `_SURROUND` variants are only defined for XP SP2 and up, but that shouldn't be a problem for us since that's all we support in Gecko anyway.

**Comment by kinetiknz** [comment]
Digging in to this further, using https://msdn.microsoft.com/en-us/library/windows/desktop/aa383745(v=vs.85).aspx as a reference...

> the `_SURROUND` variants are only defined for XP SP2 and up

More specifically, they're defined for `NTDDI_VERSION` `0x05010200` (XP SP2) up to but not including `0x05020000` (WS03) and then from `0x05020100` (WS03 SP1) onwards.

`NTDDI_VERSION ` is derived from `_WIN32_WINNT` in `sdkddkver.h` in the Windows SDK, and _WIN32_WINNT is set to `0x0502` (`_WIN32_WINNT_WS03` aka "Windows Server 2003 with SP1, Windows XP with SP2") in the Gecko build.

The trap is... `sdkddkver.h` derives `NTDDI_VERSION` by simply appending `0000` to the value of `_WIN32_WINNT`, so despite `_WIN32_WINNT_WS03` claiming to represent XP SP2 and WS03 SP1, the `NTDDI_VERSION` derived will correspond to `NTDDI_WS03,` which explicitly excludes the required `_SURROUND` definitions.

We don't hit this on AppVeyor because libcubeb's own build system uses the SDK defaults, which is the latest Windows version supported by the selected SDK.

So I think the simplest fix is to add `#define NTDDI_VERSION 0x05020100` to the top of cubeb_wasapi.cpp.

**Comment by ChunMinChang** [comment]
Thanks for the explicit diagnosis. I've modified the code by your suggestion. Thanks : )

**Comment by kinetiknz** [comment]
Thanks! I added a short comment when I merged the commit.

**Pull request closed without merging**
